// <auto-generated />
using System;
using Frontend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frontend.Migrations
{
    [DbContext(typeof(MatchPadelContext))]
    partial class MatchPadelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Frontend.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("Frontend.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DateTimeOffset")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "DateTimeOffSet");

                    b.Property<int?>("GameTypeRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeRefId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Frontend.Models.Result", b =>
                {
                    b.Property<int>("MatchRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchRefId", "UserRefId");

                    b.HasIndex("UserRefId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Frontend.Models.Set", b =>
                {
                    b.Property<int>("MatchRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamOneScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamTwoScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchRefId", "Number");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Frontend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Frontend.Models.Match", b =>
                {
                    b.HasOne("Frontend.Models.GameType", "GameType")
                        .WithMany("Matches")
                        .HasForeignKey("GameTypeRefId");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("Frontend.Models.Result", b =>
                {
                    b.HasOne("Frontend.Models.Match", "Match")
                        .WithMany("Results")
                        .HasForeignKey("MatchRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frontend.Models.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frontend.Models.Set", b =>
                {
                    b.HasOne("Frontend.Models.Match", "MatchNavigation")
                        .WithMany("Sets")
                        .HasForeignKey("MatchRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchNavigation");
                });

            modelBuilder.Entity("Frontend.Models.GameType", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Frontend.Models.Match", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Frontend.Models.User", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
